export enum AppTypes {
    INIT_APP="INIT_APP",
    END_SPLASH_ANIMATION="END_SPLASH_ANIMATION",
    CHANGE_CLIPBOARD_IMDB="CHANGE_CLIPBOARD_IMDB",
    UPDATE_MOVIE_MODEL="UPDATE_MOVIE_MODEL",
    REFRESH_LIST="REFRESH_LIST",
}

export enum AuthTypes {
    INIT_AUTH="INIT_AUTH",
    USER_SIGNED_IN="USER_SIGNED_IN",
    USER_SIGNED_OUT="USER_SIGNED_OUT",

}